// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package voltanet

// Injectors from wire.go:

// initApp init gateway application.
func initApp() (*app, func(), error) {
	events := NewEvents()
	wsHeartBeat := NewWsHeartBeat(events)
	signal := NewSignal()
	options := NewOptions()
	websocket := NewWebsocket(signal, events, wsHeartBeat, options)
	app := newApp(wsHeartBeat, websocket)
	return app, func() {
	}, nil
}
